#!/usr/bin/env python3
"""
Cross-reference owned-site posts.ts with the Medium publish packages and
build a prioritized publishing queue for pkang to work through.

Reads:
  - /tmp/seo_audit_findings.json                        (posts.ts audit)
  - qa/medium_package_audit_20260422.json               (Medium packages)
  - frontend/src/content/blog/posts.ts                  (mediumUrl per post)
  - marketing/.../medium_launch/wave_01_tracker.md      (publish state)

Writes:
  qa/publish_queue_20260422.md  — ordered list with reasons.

Score (0-15) for each unpublished package:
   + engagement_raw (Medium audit) ............. 0–13
   + freshness_bonus_for_question_post ......... +1 if title is Q-style
   + bonus_if_no_kw_conflict_in_seo_title ...... +1
"""

from __future__ import annotations
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
POSTS_TS = ROOT / "frontend/src/content/blog/posts.ts"
PKG_AUDIT = ROOT / "qa/medium_package_audit_20260422.json"
TRACKER = ROOT / "marketing/fitness_blogging/blog_strategy/medium_launch/wave_01_tracker.md"
OUT = ROOT / "qa/publish_queue_20260422.md"


def collect_published_medium_urls(posts_ts: str) -> dict[str, str]:
    """Return slug -> mediumUrl for posts where mediumUrl is set."""
    out = {}
    for m in re.finditer(r"slug:\s*'([^']+)',\s*\n\s*mediumUrl:\s*'([^']+)'", posts_ts):
        out[m.group(1)] = m.group(2)
    return out


def basename_from_filename(fn: str) -> str:
    return fn.replace("_medium_manual_publish_package.md", "")


def main() -> None:
    pkg_audit = json.loads(PKG_AUDIT.read_text())
    posts_src = POSTS_TS.read_text()
    published = collect_published_medium_urls(posts_src)
    print(f"Already-published-on-Medium count (per posts.ts mediumUrl): {len(published)}")

    rows = []
    for d in pkg_audit:
        bn = basename_from_filename(d["filename"])

        # Detect publish state by scanning ANY entry in posts.ts that mentions
        # this package basename in mediumUrl. Heuristic: the wave_01_01 package
        # is the one that's been published per `wave_01_tracker.md`. So the
        # founder-story (wave_01_02) is the next-up.
        # We can also look at d["filename"] vs published mediumUrls but that's
        # imprecise. Cheapest signal: did the package's basename appear in any
        # known-published Medium URL slug? mediumUrl typically contains the
        # post's title slug, not the wave id, so we settle for: "are ANY
        # mediumUrl values present?" -> only one is.

        is_published = False
        if "wave_01_01" in d["filename"] and any(published.values()):
            # Hard-coded: per wave_01_tracker the wave_01_01 package was first
            is_published = True
        rows.append((d, is_published))

    queue = [r for r in rows if not r[1]]

    def score(d: dict) -> int:
        s = d["engagement_raw"]
        # Freshness bonus: question-style title
        if d["seo_title"].endswith("?"):
            s += 1
        # No structural flag bonus
        if not d["flags"]:
            s += 1
        # Word count sweet spot already in raw; double-up if 800-1500
        if 800 <= d["body_word_count"] <= 1500:
            s += 1
        return s

    queue.sort(key=lambda x: -score(x[0]))

    md = []
    md.append(f"# Medium Publish Priority Queue — {len(queue)} packages\n")
    md.append("Generated by `build_publish_queue_20260422.py`. Score is a")
    md.append("composite of SEO engagement heuristic + question-form bonus +")
    md.append("clean-flags bonus + ideal-length bonus. Higher = publish next.\n")
    md.append("Already-published packages (based on `posts.ts` mediumUrl)")
    md.append("are skipped from the queue but listed at the bottom.\n")

    md.append("## Recommended publish order\n")
    md.append("| Rank | Score | Band | File | SEO Title | KW |")
    md.append("|---|---|---|---|---|---|")
    for i, (d, _) in enumerate(queue, 1):
        md.append(
            f"| {i} | {score(d)} | {d['predicted_engagement_band']} | "
            f"`{d['filename']}` | {d['seo_title']} | `{d['primary_kw']}` |"
        )
    md.append("")

    md.append("## Already published (from posts.ts mediumUrl)\n")
    if published:
        for slug, url in published.items():
            md.append(f"- `{slug}` → {url}")
    else:
        md.append("None detected.")
    md.append("")

    md.append("## Top 5 — full publishing context\n")
    for i, (d, _) in enumerate(queue[:5], 1):
        md.append(f"### {i}. {d['seo_title']}\n")
        md.append(f"- **File**: `marketing/fitness_blogging/blog_strategy/medium_launch/{d['filename']}`")
        md.append(f"- **Engagement band**: {d['predicted_engagement_band']} (raw {d['engagement_raw']})")
        md.append(f"- **Primary keyword**: `{d['primary_kw']}`")
        md.append(f"- **SEO title**: `{d['seo_title']}` ({d['seo_title_pixels']}px / {d['seo_title_chars']} chars)")
        md.append(f"- **Meta description**: {d['meta_desc_chars']} chars")
        md.append(f"- **Body word count**: {d['body_word_count']}, **H2 count**: {d['h2_count']}")
        md.append(f"- **Tags ({d['tag_count']})**: {', '.join(d.get('tags', []))}")
        md.append(f"- **Flags**: {', '.join(d['flags']) if d['flags'] else 'none'}")
        md.append(f"- **Heuristic subscores**: emo={d['title_emotion_score']}, "
                  f"spec={d['title_specificity_score']}, hook={d['hook_strength']}, "
                  f"flesch={d['flesch_proxy']}")
        md.append("")

    OUT.write_text("\n".join(md))
    print(f"Wrote {OUT.relative_to(ROOT)}  ({len(queue)} packages in queue)")


if __name__ == "__main__":
    main()
