"""Spec: SEO opener prepends for the first paragraph of 62 Medium blog posts.

Generated 2026-04-21 (subagent task).

Source: marketing/fitness_blogging/blog_strategy/seo_first_paragraph_audit.json
Rules:  marketing/fitness_blogging/blog_strategy/seo_optimization_rules.md

Each entry maps a posts.ts slug to:
  - package_basename:  wave_XX_NN_<topic> (without _medium_manual_publish_package.md)
  - primary_keyword:   exact phrase from the audit (Medium SERP target)
  - current_first:     verbatim first paragraph as it lives today
  - opener:            1-2 sentence prepend that front-loads the primary
                       keyword in the first 60 chars (ALL <= 160 chars)
  - new_first:         opener + " " + current_first  (the rewritten paragraph)

Voice: pkang. Founder-led, anti-hype, observational, dry, direct.
No banned phrases (ultimate, secret, shocking, life-changing,
transform your body, guaranteed, fast results, you wont believe,
crazy, insane).

Pattern distribution: A=22 (question + brief answer), B=15 (statement),
C=14 (how-to with "Heres how"), D=11 (yes/no with one-clause why).
"""

FIRST_PARAGRAPH_OPENERS: dict[str, dict[str, str]] = {
    "how-to-stick-to-a-diet-when-progress-slows": {
        "package_basename": "wave_01_01_consistency",
        "primary_keyword": "how to stick to a diet when progress slows down",
        "current_first": "Most people do not quit dieting because they are lazy. They quit because early progress teaches the wrong lesson, later progress gets quieter, and one loud weigh-in starts sounding like proof of failure.",
        "opener": "Here's how to stick to a diet when progress slows down without restarting every Monday. The middle is where most people quit, not the start.",
        "new_first": "Here's how to stick to a diet when progress slows down without restarting every Monday. The middle is where most people quit, not the start. Most people do not quit dieting because they are lazy. They quit because early progress teaches the wrong lesson, later progress gets quieter, and one loud weigh-in starts sounding like proof of failure.",
    },
    "how-i-lost-50-kg-middle-of-diet": {
        "package_basename": "wave_01_02_founder_story",
        "primary_keyword": "how I lost 50 kg",
        "current_first": "I lost 50 kg, but the hardest part was not starting. It was the slow middle where progress was real, but hard to trust. That is why I built Devenira around weekly proof.",
        "opener": "How I lost 50 kg, in one honest sentence: slowly, and mostly in the unglamorous middle. The start wasn't the hard part.",
        "new_first": "How I lost 50 kg, in one honest sentence: slowly, and mostly in the unglamorous middle. The start wasn't the hard part. I lost 50 kg, but the hardest part was not starting. It was the slow middle where progress was real, but hard to trust. That is why I built Devenira around weekly proof.",
    },
    "why-cant-i-see-weight-loss-in-the-mirror": {
        "package_basename": "wave_01_03_mirror",
        "primary_keyword": "why can't I see my weight loss in the mirror",
        "current_first": "If you see your body every day, the mirror is often the last place that will give you reassurance. That does not mean progress is not happening. It means the mirror is a terrible historian.",
        "opener": "Why can't I see my weight loss in the mirror, even when the scale and the clothes agree? Daily exposure hides the gradient.",
        "new_first": "Why can't I see my weight loss in the mirror, even when the scale and the clothes agree? Daily exposure hides the gradient. If you see your body every day, the mirror is often the last place that will give you reassurance. That does not mean progress is not happening. It means the mirror is a terrible historian.",
    },
    "should-i-weigh-myself-every-day-on-a-diet": {
        "package_basename": "wave_01_04_weighin",
        "primary_keyword": "should I weigh myself every day on a diet",
        "current_first": "The scale is not useless. But one loud reading can trigger a lot of bad decisions if you let it become a verdict instead of a data point.",
        "opener": "Should you weigh yourself every day on a diet? It depends on whether one bad reading derails the rest of the week.",
        "new_first": "Should you weigh yourself every day on a diet? It depends on whether one bad reading derails the rest of the week. The scale is not useless. But one loud reading can trigger a lot of bad decisions if you let it become a verdict instead of a data point.",
    },
    "are-cheat-days-bad-for-weight-loss": {
        "package_basename": "wave_01_06_cheat_day",
        "primary_keyword": "are cheat days bad for weight loss",
        "current_first": "Some people binge on cheat days and some do not. The difference is often not willpower. It is whether the body and the food environment are still primed for rebound.",
        "opener": "Are cheat days bad for weight loss? Not for everyone — and the difference says more about the rest of your week than your willpower.",
        "new_first": "Are cheat days bad for weight loss? Not for everyone — and the difference says more about the rest of your week than your willpower. Some people binge on cheat days and some do not. The difference is often not willpower. It is whether the body and the food environment are still primed for rebound.",
    },
    "why-is-my-appetite-stronger-on-a-diet": {
        "package_basename": "wave_02_01_appetite_louder",
        "primary_keyword": "why is my appetite stronger on a diet",
        "current_first": "If dieting has made food feel louder, that does not automatically mean you are weak. Appetite often gets more chaotic when the system becomes too restrictive, repetitive, or emotionally brittle.",
        "opener": "Why is my appetite stronger on a diet, even when I'm eating enough on paper? Restriction makes the brain louder, not just the stomach.",
        "new_first": "Why is my appetite stronger on a diet, even when I'm eating enough on paper? Restriction makes the brain louder, not just the stomach. If dieting has made food feel louder, that does not automatically mean you are weak. Appetite often gets more chaotic when the system becomes too restrictive, repetitive, or emotionally brittle.",
    },
    "how-to-track-body-transformation-without-the-scale": {
        "package_basename": "wave_02_02_how-to-track-body-transformation-without-obsessing-over-the-scale",
        "primary_keyword": "how to track body transformation without the scale",
        "current_first": "If you want to know whether your body is actually changing, you need a better system than checking the scale and the mirror every day. A simple weekly evidence loop works better.",
        "opener": "Here's how to track body transformation without the scale, with one weekly evidence loop instead of a daily morning verdict.",
        "new_first": "Here's how to track body transformation without the scale, with one weekly evidence loop instead of a daily morning verdict. If you want to know whether your body is actually changing, you need a better system than checking the scale and the mirror every day. A simple weekly evidence loop works better.",
    },
    "why-does-the-scale-go-up-when-i-barely-eat": {
        "package_basename": "wave_02_03_why-it-feels-like-you-gain-weight-even-when-you-barely-eat",
        "primary_keyword": "why does the scale go up when I barely eat",
        "current_first": "A rude weigh-in can turn one morning into a small identity crisis. But scale weight and fat gain are not always the same story.",
        "opener": "Why does the scale go up when you're barely eating? Almost always: water, sodium, or a delayed bathroom — not fat.",
        "new_first": "Why does the scale go up when you're barely eating? Almost always: water, sodium, or a delayed bathroom — not fat. A rude weigh-in can turn one morning into a small identity crisis. But scale weight and fat gain are not always the same story.",
    },
    "what-counts-as-a-weight-loss-plateau": {
        "package_basename": "wave_02_04_what-actually-counts-as-a-weight-loss-plateau",
        "primary_keyword": "what counts as a weight loss plateau",
        "current_first": "A slower scale is not automatically a plateau. Sometimes progress just stopped flattering you and started looking like real life.",
        "opener": "What counts as a weight loss plateau is narrower than people think. Most slow weeks are not plateaus — just real life.",
        "new_first": "What counts as a weight loss plateau is narrower than people think. Most slow weeks are not plateaus — just real life. A slower scale is not automatically a plateau. Sometimes progress just stopped flattering you and started looking like real life.",
    },
    "is-losing-5kg-in-a-week-water-weight": {
        "package_basename": "wave_02_05_why-losing-5kg-in-a-week-usually-means-water-not-fat",
        "primary_keyword": "is losing 5kg in a week water weight",
        "current_first": "Rapid weight loss sounds impressive, but most short-term scale drops are driven by water, not miracle fat loss. The timescale matters more than the headline.",
        "opener": "Is losing 5kg in a week water weight? Almost always — the body cannot legitimately lose that much fat in seven days.",
        "new_first": "Is losing 5kg in a week water weight? Almost always — the body cannot legitimately lose that much fat in seven days. Rapid weight loss sounds impressive, but most short-term scale drops are driven by water, not miracle fat loss. The timescale matters more than the headline.",
    },
    "why-am-i-not-losing-weight-anymore": {
        "package_basename": "wave_02_06_the-most-important-reason-you-think-youre-not-losing-weight",
        "primary_keyword": "why am I not losing weight anymore",
        "current_first": "Many people think they are not losing weight because the process failed. More often, the dramatic early phase ended and their patience failed first.",
        "opener": "Why am I not losing weight anymore, after the early weeks worked? Usually the plan didn't break — the early phase just ended.",
        "new_first": "Why am I not losing weight anymore, after the early weeks worked? Usually the plan didn't break — the early phase just ended. Many people think they are not losing weight because the process failed. More often, the dramatic early phase ended and their patience failed first.",
    },
    "skinny-fat-normal-weight-high-body-fat": {
        "package_basename": "wave_02_07_the-scale-can-say-normal-and-still-tell-you-nothing-useful",
        "primary_keyword": "skinny fat normal weight but high body fat",
        "current_first": "A normal weight does not guarantee that someone feels lean, strong, or at ease in their body. The scale is often too crude to explain what they are actually struggling with.",
        "opener": "Skinny fat — normal weight but high body fat — is the version of unfit the scale never reports. The number is fine; the composition isn't.",
        "new_first": "Skinny fat — normal weight but high body fat — is the version of unfit the scale never reports. The number is fine; the composition isn't. A normal weight does not guarantee that someone feels lean, strong, or at ease in their body. The scale is often too crude to explain what they are actually struggling with.",
    },
    "progress-update-body-changes-slower-than-mind": {
        "package_basename": "wave_02_08_progress-update-2-the-body-changed-slower-than-my-head-did",
        "primary_keyword": "body changes slower than mind during weight loss",
        "current_first": "The biggest visible change was not actually the most important one. The body changed, yes, but the bigger shift was that panic became less convincing.",
        "opener": "The body changes slower than the mind during weight loss — and most of the time, it's the mind that quits first.",
        "new_first": "The body changes slower than the mind during weight loss — and most of the time, it's the mind that quits first. The biggest visible change was not actually the most important one. The body changed, yes, but the bigger shift was that panic became less convincing.",
    },
    "how-to-know-youre-losing-weight-without-the-scale": {
        "package_basename": "wave_02_09_dont-trust-the-scale-heres-what-actually-proves-youre-losing-weight",
        "primary_keyword": "how to know you're losing weight without the scale",
        "current_first": "A lot of people want fat loss to come with a receipt. But the scale is one witness, not the whole case. Real proof often shows up in shape, fit, firmness, and repeated visual change.",
        "opener": "Here's how to know you're losing weight without the scale, with proof that holds up across a week. The receipt is rarely a number.",
        "new_first": "Here's how to know you're losing weight without the scale, with proof that holds up across a week. The receipt is rarely a number. A lot of people want fat loss to come with a receipt. But the scale is one witness, not the whole case. Real proof often shows up in shape, fit, firmness, and repeated visual change.",
    },
    "how-to-handle-hunger-pangs-on-a-diet": {
        "package_basename": "wave_02_10_you-do-not-need-to-love-hunger-you-need-to-understand-it",
        "primary_keyword": "how to handle hunger pangs on a diet",
        "current_first": "You do not need to enjoy hunger to diet well. You need to understand what kind of hunger you are dealing with, and what kind of food pattern keeps making it louder.",
        "opener": "Here's how to handle hunger pangs on a diet without treating every signal as a failure of willpower. Most pangs want context, not food.",
        "new_first": "Here's how to handle hunger pangs on a diet without treating every signal as a failure of willpower. Most pangs want context, not food. You do not need to enjoy hunger to diet well. You need to understand what kind of hunger you are dealing with, and what kind of food pattern keeps making it louder.",
    },
    "why-cant-i-sleep-on-a-calorie-deficit": {
        "package_basename": "wave_02_11_if-your-diet-broke-your-sleep-it-is-not-discipline-anymore",
        "primary_keyword": "why can't I sleep on a calorie deficit",
        "current_first": "If dieting and training hard left you exhausted but unable to sleep, the answer is probably not to become even stricter. Sometimes the plan is not impressive. It is just under-fueling a body asked to do too much.",
        "opener": "Why can't I sleep on a calorie deficit, even when I'm exhausted? Usually because the deficit is bigger than the body wants to admit.",
        "new_first": "Why can't I sleep on a calorie deficit, even when I'm exhausted? Usually because the deficit is bigger than the body wants to admit. If dieting and training hard left you exhausted but unable to sleep, the answer is probably not to become even stricter. Sometimes the plan is not impressive. It is just under-fueling a body asked to do too much.",
    },
    "does-one-bad-day-ruin-a-diet": {
        "package_basename": "wave_02_12_youve-been-told-one-bad-day-wont-hurt-but-thats-only-half-the-truth",
        "primary_keyword": "does one bad day ruin a diet",
        "current_first": "One bad day usually does less damage than several bad days in a row. The problem is how quickly that technically true idea turns into behaviorally disastrous cheat-day logic.",
        "opener": "Does one bad day ruin a diet? Almost never — but the next three days decide whether one bad day stays one bad day.",
        "new_first": "Does one bad day ruin a diet? Almost never — but the next three days decide whether one bad day stays one bad day. One bad day usually does less damage than several bad days in a row. The problem is how quickly that technically true idea turns into behaviorally disastrous cheat-day logic.",
    },
    "do-obese-people-lose-weight-slower": {
        "package_basename": "wave_02_13_do-people-who-have-been-obese-for-years-lose-weight-more-slowly",
        "primary_keyword": "do obese people lose weight slower than others",
        "current_first": "If weight came on slowly over years, more of it is usually true fat rather than temporary water. That can make the process feel heavier, but it does not mean your body is uniquely cursed.",
        "opener": "Do obese people lose weight slower than others? On the scale, sometimes the opposite — but the fat under it tells a longer story.",
        "new_first": "Do obese people lose weight slower than others? On the scale, sometimes the opposite — but the fat under it tells a longer story. If weight came on slowly over years, more of it is usually true fat rather than temporary water. That can make the process feel heavier, but it does not mean your body is uniquely cursed.",
    },
    "how-to-trust-slow-weight-loss-progress": {
        "package_basename": "wave_03_01_the-quiet-erosion-of-not-believing-your-progress",
        "primary_keyword": "how to trust slow weight loss progress",
        "current_first": "The biggest losses of my own program did not happen on the worst days. They happened on the quiet ones, in the unremarkable gap between checkpoints where doubt arrived wearing the costume of maturity.",
        "opener": "Here's how to trust slow weight loss progress when the days stop feeling like proof. Most of the work happens in the quiet stretch.",
        "new_first": "Here's how to trust slow weight loss progress when the days stop feeling like proof. Most of the work happens in the quiet stretch. The biggest losses of my own program did not happen on the worst days. They happened on the quiet ones, in the unremarkable gap between checkpoints where doubt arrived wearing the costume of maturity.",
    },
    "why-progress-photos-dont-show-progress": {
        "package_basename": "wave_03_02_progress-photos-can-lie-as-much-as-the-mirror-does",
        "primary_keyword": "why progress photos don't show progress",
        "current_first": "People who would never trust a single weigh-in will completely trust a single photo. They should not. Lighting, posture, and last night's dinner can fake an entire month of progress in either direction.",
        "opener": "Why progress photos don't show progress half the time has nothing to do with the body. It's lighting, posture, and last night's dinner.",
        "new_first": "Why progress photos don't show progress half the time has nothing to do with the body. It's lighting, posture, and last night's dinner. People who would never trust a single weigh-in will completely trust a single photo. They should not. Lighting, posture, and last night's dinner can fake an entire month of progress in either direction.",
    },
    "why-does-restriction-make-cravings-worse": {
        "package_basename": "wave_03_03_is-this-craving-the-food-or-the-deprivation-talking",
        "primary_keyword": "why does restriction make cravings worse",
        "current_first": "After about a year of careful eating, I noticed something I did not expect. The foods I missed most were not the foods I had loved most. They were the foods I had been most strict with myself about.",
        "opener": "Why does restriction make cravings worse? Usually because the food you forbid becomes the food your brain rehearses.",
        "new_first": "Why does restriction make cravings worse? Usually because the food you forbid becomes the food your brain rehearses. After about a year of careful eating, I noticed something I did not expect. The foods I missed most were not the foods I had loved most. They were the foods I had been most strict with myself about.",
    },
    "why-does-the-same-weight-feel-different-as-you-age": {
        "package_basename": "wave_03_04_the-same-number-on-the-scale-feels-different-at-30-than-at-20",
        "primary_keyword": "why does the same weight feel different as you age",
        "current_first": "The first time I weighed exactly 75 kg, I was 22. The second time I weighed exactly 75 kg, I was around 30. The number was identical. The body underneath it was not. Not even close.",
        "opener": "Why does the same weight feel different as you age? Same number on the scale, different body underneath it.",
        "new_first": "Why does the same weight feel different as you age? Same number on the scale, different body underneath it. The first time I weighed exactly 75 kg, I was 22. The second time I weighed exactly 75 kg, I was around 30. The number was identical. The body underneath it was not. Not even close.",
    },
    "non-scale-victories-weight-loss": {
        "package_basename": "wave_03_05_the-small-wins-between-progress-updates-are-the-real-program",
        "primary_keyword": "non scale victories weight loss",
        "current_first": "The big numbers were not the program. The 50 kg loss is the headline. But the program — the thing that actually moved the body — was almost entirely made of weeks where nothing photogenic happened.",
        "opener": "Non scale victories in weight loss are the boring half of the program — and the half that actually moves the body.",
        "new_first": "Non scale victories in weight loss are the boring half of the program — and the half that actually moves the body. The big numbers were not the program. The 50 kg loss is the headline. But the program — the thing that actually moved the body — was almost entirely made of weeks where nothing photogenic happened.",
    },
    "first-month-of-maintenance-after-weight-loss": {
        "package_basename": "wave_03_06_the-first-month-of-maintenance-feels-nothing-like-the-diet",
        "primary_keyword": "first month of maintenance after weight loss",
        "current_first": "The diet has a finish line painted on it. Maintenance does not. That single difference is what makes the first month after the cut feel completely unlike anything you spent the cut preparing for.",
        "opener": "The first month of maintenance after weight loss feels nothing like the diet. The finish line is gone, and the rules quietly change.",
        "new_first": "The first month of maintenance after weight loss feels nothing like the diet. The finish line is gone, and the rules quietly change. The diet has a finish line painted on it. Maintenance does not. That single difference is what makes the first month after the cut feel completely unlike anything you spent the cut preparing for.",
    },
    "why-am-i-hungry-at-night-but-not-during-the-day": {
        "package_basename": "wave_03_07_why-does-my-hunger-spike-at-night-when-i-was-fine-all-day",
        "primary_keyword": "why am I hungry at night but not during the day",
        "current_first": "The cleanest day on paper can end at 9 p.m. with you standing at the open fridge. The day was a number. The evening was a person. A practical Q&A on the night-hunger spike.",
        "opener": "Why am I hungry at night but not during the day, even on a clean food day? The evening is where the day's restriction comes due.",
        "new_first": "Why am I hungry at night but not during the day, even on a clean food day? The evening is where the day's restriction comes due. The cleanest day on paper can end at 9 p.m. with you standing at the open fridge. The day was a number. The evening was a person. A practical Q&A on the night-hunger spike.",
    },
    "am-i-really-in-a-plateau-or-tracking-wrong": {
        "package_basename": "wave_03_08_the-plateau-that-was-actually-an-honesty-problem",
        "primary_keyword": "am I really in a plateau or am I tracking wrong",
        "current_first": "Most plateaus are real. But a meaningful share of the plateaus people report are not the body refusing to lose weight. They are the tracking refusing to admit what the day actually contained.",
        "opener": "Am I really in a plateau or am I tracking wrong? Most plateaus are real — but a meaningful share are the food log, not the body.",
        "new_first": "Am I really in a plateau or am I tracking wrong? Most plateaus are real — but a meaningful share are the food log, not the body. Most plateaus are real. But a meaningful share of the plateaus people report are not the body refusing to lose weight. They are the tracking refusing to admit what the day actually contained.",
    },
    "life-after-50kg-weight-loss": {
        "package_basename": "wave_03_09_progress-update-4-the-body-finally-stopped-being-the-loud-thing",
        "primary_keyword": "life after 50kg weight loss",
        "current_first": "Four months past the last update. The numbers moved less. The relationship moved more. A founder check-in on the phase where the body finally goes quiet.",
        "opener": "Life after 50kg weight loss is quieter than the highlight reel sells it. The dramatic part ends; the body just is.",
        "new_first": "Life after 50kg weight loss is quieter than the highlight reel sells it. The dramatic part ends; the body just is. Four months past the last update. The numbers moved less. The relationship moved more. A founder check-in on the phase where the body finally goes quiet.",
    },
    "clothes-fit-better-but-scale-is-the-same": {
        "package_basename": "wave_03_10_clothes-tell-you-the-truth-the-mirror-cannot",
        "primary_keyword": "why my clothes fit better but scale is the same",
        "current_first": "The mirror lies fast. The scale is noisy. The clothes do not negotiate. They either fit or they do not. There is no light, no posture, no time of day that changes the answer.",
        "opener": "Why do my clothes fit better but the scale is the same? Body composition shifted; total mass didn't — and the clothes don't negotiate.",
        "new_first": "Why do my clothes fit better but the scale is the same? Body composition shifted; total mass didn't — and the clothes don't negotiate. The mirror lies fast. The scale is noisy. The clothes do not negotiate. They either fit or they do not. There is no light, no posture, no time of day that changes the answer.",
    },
    "how-to-get-back-on-track-after-a-bad-weekend": {
        "package_basename": "wave_03_11_the-bad-weekend-that-finally-taught-me-something",
        "primary_keyword": "how to get back on track after a bad weekend",
        "current_first": "I had been clean for six weeks. Then a Friday dinner became a Saturday lunch which became a Saturday night. The damage was small. What the weekend exposed was the whole story.",
        "opener": "Here's how to get back on track after a bad weekend without turning Monday into punishment. The fix isn't dramatic.",
        "new_first": "Here's how to get back on track after a bad weekend without turning Monday into punishment. The fix isn't dramatic. I had been clean for six weeks. Then a Friday dinner became a Saturday lunch which became a Saturday night. The damage was small. What the weekend exposed was the whole story.",
    },
    "how-to-stop-mirror-checking-on-a-diet": {
        "package_basename": "wave_03_12_how-to-go-on-a-mirror-diet-when-the-real-diet-is-getting-loud",
        "primary_keyword": "how to stop mirror checking on a diet",
        "current_first": "There is a phase in most cuts where the diet is working and the mirror is getting louder. The fix is to look less, look better, and look in fewer states.",
        "opener": "Here's how to stop mirror checking on a diet that's actually working: look less, look better, and look in fewer states.",
        "new_first": "Here's how to stop mirror checking on a diet that's actually working: look less, look better, and look in fewer states. There is a phase in most cuts where the diet is working and the mirror is getting louder. The fix is to look less, look better, and look in fewer states.",
    },
    "do-i-have-to-meal-prep-to-lose-weight": {
        "package_basename": "wave_03_13_do-i-actually-have-to-meal-prep-to-lose-weight",
        "primary_keyword": "do I have to meal prep to lose weight",
        "current_first": "The honest answer is no. The more useful answer is that you have to solve the same underlying problem meal prep is solving — decision fatigue, macro reliability, friction. Sunday is one tool among several.",
        "opener": "Do I have to meal prep to lose weight? No — but you have to solve the problem meal prep is solving, with or without Sunday containers.",
        "new_first": "Do I have to meal prep to lose weight? No — but you have to solve the problem meal prep is solving, with or without Sunday containers. The honest answer is no. The more useful answer is that you have to solve the same underlying problem meal prep is solving — decision fatigue, macro reliability, friction. Sunday is one tool among several.",
    },
    "why-adding-cardio-to-a-cut-backfires": {
        "package_basename": "wave_03_14_why-adding-cardio-to-a-cut-can-backfire-faster-than-you-think",
        "primary_keyword": "why adding cardio to a cut can backfire",
        "current_first": "Cardio looks like the obvious add when fat loss slows. It often makes things worse, not better. The reasons are physiological, behavioral, and almost never about the cardio itself.",
        "opener": "Why adding cardio to a cut can backfire is rarely about the cardio. It's usually about what the cardio costs everywhere else.",
        "new_first": "Why adding cardio to a cut can backfire is rarely about the cardio. It's usually about what the cardio costs everywhere else. Cardio looks like the obvious add when fat loss slows. It often makes things worse, not better. The reasons are physiological, behavioral, and almost never about the cardio itself.",
    },
    "daily-weighing-eating-disorder-risk": {
        "package_basename": "wave_03_15_weighing-yourself-every-day-can-be-a-trap-not-a-discipline",
        "primary_keyword": "daily weighing eating disorder risk",
        "current_first": "The advice to weigh yourself every day is delivered with the tone of discipline. For a meaningful share of people, it is the trap that wrecks the program.",
        "opener": "The daily weighing eating disorder risk doesn't get talked about because the advice sounds disciplined. For some people it isn't.",
        "new_first": "The daily weighing eating disorder risk doesn't get talked about because the advice sounds disciplined. For some people it isn't. The advice to weigh yourself every day is delivered with the tone of discipline. For a meaningful share of people, it is the trap that wrecks the program.",
    },
    "does-cutting-sodium-cause-water-retention": {
        "package_basename": "wave_03_16_why-cutting-sodium-too-hard-can-backfire",
        "primary_keyword": "does cutting sodium cause water retention rebound",
        "current_first": "There is a move every dieter discovers within the first month: cut sodium hard, watch the scale drop. It feels like discipline. It is mostly water moving around, and it teaches you to chase the wrong signal.",
        "opener": "Does cutting sodium cause water retention rebound? Often — and the rebound usually erases the drop within a week.",
        "new_first": "Does cutting sodium cause water retention rebound? Often — and the rebound usually erases the drop within a week. There is a move every dieter discovers within the first month: cut sodium hard, watch the scale drop. It feels like discipline. It is mostly water moving around, and it teaches you to chase the wrong signal.",
    },
    "appetite-returns-during-maintenance": {
        "package_basename": "wave_03_17_the-week-my-appetite-came-back-during-maintenance",
        "primary_keyword": "appetite returns during maintenance after weight loss",
        "current_first": "Five months into maintenance, my appetite came back. Not as failure. As a normal part of the body finishing the work the cut started. Here is what that week actually looked like — and what I almost did wrong.",
        "opener": "When appetite returns during maintenance after weight loss, it isn't failure. It is the body finishing what the cut started.",
        "new_first": "When appetite returns during maintenance after weight loss, it isn't failure. It is the body finishing what the cut started. Five months into maintenance, my appetite came back. Not as failure. As a normal part of the body finishing the work the cut started. Here is what that week actually looked like — and what I almost did wrong.",
    },
    "does-one-bad-meal-ruin-a-diet": {
        "package_basename": "wave_03_18_when-does-one-bad-meal-actually-become-a-slip",
        "primary_keyword": "does one bad meal ruin a diet",
        "current_first": "People treat one bad meal and a slip like they are the same thing. They are not. The meal is the trigger. The slip is everything you do in the 48 hours after.",
        "opener": "Does one bad meal ruin a diet? The meal almost never does. The 48 hours after it usually do.",
        "new_first": "Does one bad meal ruin a diet? The meal almost never does. The 48 hours after it usually do. People treat one bad meal and a slip like they are the same thing. They are not. The meal is the trigger. The slip is everything you do in the 48 hours after.",
    },
    "why-am-i-so-hungry-after-lifting-weights": {
        "package_basename": "wave_03_19_your-appetite-scales-with-training-volume-not-with-weight",
        "primary_keyword": "why am I so hungry after lifting weights",
        "current_first": "Appetite is not a function of how much you weigh. It is a function of how much you trained, how you slept, and what your body is rebuilding. The scale is not what your hunger is reading.",
        "opener": "Why am I so hungry after lifting weights, even on weeks the scale didn't move? Hunger reads training volume, not body weight.",
        "new_first": "Why am I so hungry after lifting weights, even on weeks the scale didn't move? Hunger reads training volume, not body weight. Appetite is not a function of how much you weigh. It is a function of how much you trained, how you slept, and what your body is rebuilding. The scale is not what your hunger is reading.",
    },
    "when-does-a-diet-become-a-lifestyle": {
        "package_basename": "wave_03_20_the-day-i-realized-the-program-was-just-my-life-now",
        "primary_keyword": "when does a diet become a lifestyle",
        "current_first": "There is a quiet moment when the program stops being a project and starts being your life. The shift is not announced. It is noticed weeks later, by accident.",
        "opener": "When does a diet become a lifestyle? Quietly. You usually notice weeks after it has already happened.",
        "new_first": "When does a diet become a lifestyle? Quietly. You usually notice weeks after it has already happened. There is a quiet moment when the program stops being a project and starts being your life. The shift is not announced. It is noticed weeks later, by accident.",
    },
    "why-am-i-working-out-but-not-losing-weight": {
        "package_basename": "wave_catchup_008_exercise-isnt-shrinking-you-the-way-you-expected",
        "primary_keyword": "why am I working out but not losing weight",
        "current_first": "Exercise is not a shrinking machine. It is a body-composition machine, a metabolism-shaping machine, a stress-processing machine. What it is not, consistently, is a quick way to remove fat.",
        "opener": "Why am I working out but not losing weight? Because exercise reshapes the body more than it shrinks it — and the scale doesn't reward that.",
        "new_first": "Why am I working out but not losing weight? Because exercise reshapes the body more than it shrinks it — and the scale doesn't reward that. Exercise is not a shrinking machine. It is a body-composition machine, a metabolism-shaping machine, a stress-processing machine. What it is not, consistently, is a quick way to remove fat.",
    },
    "why-is-the-middle-of-weight-loss-the-hardest": {
        "package_basename": "wave_catchup_009_the-unglamorous-middle-of-transformation",
        "primary_keyword": "why is the middle of weight loss the hardest",
        "current_first": "The before photo is easy. The after photo is easy. The six months between them is where everybody quits.",
        "opener": "Why is the middle of weight loss the hardest stretch? The dramatic feedback is gone and the work hasn't ended.",
        "new_first": "Why is the middle of weight loss the hardest stretch? The dramatic feedback is gone and the work hasn't ended. The before photo is easy. The after photo is easy. The six months between them is where everybody quits.",
    },
    "is-my-stomach-bloat-or-fat": {
        "package_basename": "wave_catchup_010_is-it-bloat-or-is-it-fat",
        "primary_keyword": "how to tell if my stomach is bloat or fat",
        "current_first": "This is one of the most useful questions anyone can ask. It is also one of the most mis-answered.",
        "opener": "Here's how to tell if your stomach is bloat or fat: time it across days, not minutes. Bloat moves; fat doesn't.",
        "new_first": "Here's how to tell if your stomach is bloat or fat: time it across days, not minutes. Bloat moves; fat doesn't. This is one of the most useful questions anyone can ask. It is also one of the most mis-answered.",
    },
    "how-to-break-a-weight-loss-plateau": {
        "package_basename": "wave_catchup_011_a-plateau-is-a-data-point-not-a-failure",
        "primary_keyword": "how to break a weight loss plateau",
        "current_first": "Most people read a plateau as their body firing them. It is not. A plateau is the cleanest feedback your body ever gives you. Most people are too frustrated to read it.",
        "opener": "Here's how to break a weight loss plateau without escalating to punishment-mode. The fix is rarely more discipline.",
        "new_first": "Here's how to break a weight loss plateau without escalating to punishment-mode. The fix is rarely more discipline. Most people read a plateau as their body firing them. It is not. A plateau is the cleanest feedback your body ever gives you. Most people are too frustrated to read it.",
    },
    "why-does-my-body-look-different-from-different-angles": {
        "package_basename": "wave_catchup_012_the-body-looks-different-from-behind",
        "primary_keyword": "why does my body look different from different angles",
        "current_first": "I spent eight months watching the front of my body in a mirror and thinking nothing was happening. Then my brother took a photo of me from behind at a wedding. It was a different body.",
        "opener": "Why does my body look different from different angles? Front view rewards bad lighting; back view tells the truth most of the time.",
        "new_first": "Why does my body look different from different angles? Front view rewards bad lighting; back view tells the truth most of the time. I spent eight months watching the front of my body in a mirror and thinking nothing was happening. Then my brother took a photo of me from behind at a wedding. It was a different body.",
    },
    "past-the-messy-middle-of-weight-loss": {
        "package_basename": "wave_catchup_013_progress-update-3-past-the-messy-middle",
        "primary_keyword": "past the messy middle of weight loss",
        "current_first": "Four months past the messy middle. Down roughly 15 kg from the highest. The head is still catching up to the body. This is what that actually feels like.",
        "opener": "Past the messy middle of weight loss, the work changes shape. The body keeps moving; the head finally starts to catch up.",
        "new_first": "Past the messy middle of weight loss, the work changes shape. The body keeps moving; the head finally starts to catch up. Four months past the messy middle. Down roughly 15 kg from the highest. The head is still catching up to the body. This is what that actually feels like.",
    },
    "how-to-stop-using-exercise-as-punishment": {
        "package_basename": "wave_catchup_014_when-the-workout-becomes-therapy-not-punishment",
        "primary_keyword": "how to stop using exercise as punishment",
        "current_first": "For most of my life, the workout was a receipt. I overate on Saturday. I earned the treadmill on Monday. That kind of training can still produce results. It cannot produce peace.",
        "opener": "Here's how to stop using exercise as punishment: change what the next training session is paying for.",
        "new_first": "Here's how to stop using exercise as punishment: change what the next training session is paying for. For most of my life, the workout was a receipt. I overate on Saturday. I earned the treadmill on Monday. That kind of training can still produce results. It cannot produce peace.",
    },
    "is-maintenance-hunger-different-from-diet-hunger": {
        "package_basename": "wave_catchup_015_hunger-in-maintenance-is-different-from-hunger-on-a-diet",
        "primary_keyword": "is maintenance hunger different from diet hunger",
        "current_first": "Maintenance hunger is not the same signal as dieting hunger. Reading them the same way is one of the main reasons people regain weight within six months of reaching their goal.",
        "opener": "Is maintenance hunger different from diet hunger? Yes — and reading them the same way is a fast route back to regain.",
        "new_first": "Is maintenance hunger different from diet hunger? Yes — and reading them the same way is a fast route back to regain. Maintenance hunger is not the same signal as dieting hunger. Reading them the same way is one of the main reasons people regain weight within six months of reaching their goal.",
    },
    "why-some-people-never-gain-weight-no-matter-what": {
        "package_basename": "wave_catchup_016_the-friend-who-never-diets-and-never-gains",
        "primary_keyword": "why do some people never gain weight no matter what they eat",
        "current_first": "Everyone has that friend. Eats whatever. Never seems to gain. Never goes to the gym except in theory. Has the same body in September that they had in May. You do not, and you are furious about it.",
        "opener": "Why do some people never gain weight no matter what they eat? Genetics is part of it, but most of the gap is unmeasured behavior.",
        "new_first": "Why do some people never gain weight no matter what they eat? Genetics is part of it, but most of the gap is unmeasured behavior. Everyone has that friend. Eats whatever. Never seems to gain. Never goes to the gym except in theory. Has the same body in September that they had in May. You do not, and you are furious about it.",
    },
    "how-do-you-know-youve-reached-set-point": {
        "package_basename": "wave_catchup_017_how-do-you-know-when-youve-reached-your-set-point",
        "primary_keyword": "how do you know you've reached your set point weight",
        "current_first": "A set point is one of the more misused ideas in dieting conversations. It is useful when understood correctly. It becomes an excuse when it is not.",
        "opener": "How do you know you've reached your set point weight, and not just a slow week? The set point is a slower signal than people use it as.",
        "new_first": "How do you know you've reached your set point weight, and not just a slow week? The set point is a slower signal than people use it as. A set point is one of the more misused ideas in dieting conversations. It is useful when understood correctly. It becomes an excuse when it is not.",
    },
    "why-do-i-weigh-more-at-night": {
        "package_basename": "wave_catchup_018_the-scale-lies-differently-in-the-morning-than-in-the-evening",
        "primary_keyword": "why do I weigh more at night than in the morning",
        "current_first": "Most people weigh themselves at one specific time and treat that number as the truth. It is not the truth. It is one sample.",
        "opener": "Why do I weigh more at night than in the morning? Food, water, and salt move through you all day; the morning is just the lowest sample.",
        "new_first": "Why do I weigh more at night than in the morning? Food, water, and salt move through you all day; the morning is just the lowest sample. Most people weigh themselves at one specific time and treat that number as the truth. It is not the truth. It is one sample.",
    },
    "does-bad-sleep-ruin-weight-loss": {
        "package_basename": "wave_catchup_019_sleep-debt-ruins-a-week-of-dieting-in-three-nights",
        "primary_keyword": "does bad sleep ruin weight loss",
        "current_first": "I had a clean Monday, Tuesday, and Wednesday of eating. By Saturday, the week looked like a disaster. Three bad nights of sleep were the reason.",
        "opener": "Does bad sleep ruin weight loss? Three short nights can make a clean week of eating look like a binge week on the scale.",
        "new_first": "Does bad sleep ruin weight loss? Three short nights can make a clean week of eating look like a binge week on the scale. I had a clean Monday, Tuesday, and Wednesday of eating. By Saturday, the week looked like a disaster. Three bad nights of sleep were the reason.",
    },
    "do-vegetables-help-you-feel-full-on-a-diet": {
        "package_basename": "wave_catchup_020_the-quiet-role-vegetables-play-in-staying-full",
        "primary_keyword": "do vegetables help you feel full on a diet",
        "current_first": "Protein gets all the press. Fats get the moral arguments. Carbs get the fear. Vegetables get a vague eat-more-of-them and then nothing. The food that quietly decides whether your diet feels tolerable is usually the vegetables.",
        "opener": "Do vegetables help you feel full on a diet? Quietly, yes — they're the food that decides whether the day feels survivable.",
        "new_first": "Do vegetables help you feel full on a diet? Quietly, yes — they're the food that decides whether the day feels survivable. Protein gets all the press. Fats get the moral arguments. Carbs get the fear. Vegetables get a vague eat-more-of-them and then nothing. The food that quietly decides whether your diet feels tolerable is usually the vegetables.",
    },
    "how-to-stop-a-binge-from-becoming-a-binge-week": {
        "package_basename": "wave_catchup_021_how-do-i-stop-a-binge-from-becoming-a-binge-week",
        "primary_keyword": "how to stop a binge from becoming a binge week",
        "current_first": "One binge does not wreck a diet. The week after a binge wrecks a diet. This is the specific rescue plan.",
        "opener": "Here's how to stop a binge from becoming a binge week. The first 48 hours after the binge are the actual rescue plan.",
        "new_first": "Here's how to stop a binge from becoming a binge week. The first 48 hours after the binge are the actual rescue plan. One binge does not wreck a diet. The week after a binge wrecks a diet. This is the specific rescue plan.",
    },
    "why-do-others-notice-my-weight-loss-before-me": {
        "package_basename": "wave_catchup_022_you-look-different-to-other-people-before-yourself",
        "primary_keyword": "why do others notice my weight loss before me",
        "current_first": "People you have not seen in a few months will notice your body has changed. You will not have noticed yet. This is not modesty. It is not vanity. It is how your brain is built.",
        "opener": "Why do others notice my weight loss before me? Because your brain updates the body image last, not first.",
        "new_first": "Why do others notice my weight loss before me? Because your brain updates the body image last, not first. People you have not seen in a few months will notice your body has changed. You will not have noticed yet. This is not modesty. It is not vanity. It is how your brain is built.",
    },
    "why-do-you-lose-so-much-weight-first-week": {
        "package_basename": "wave_catchup_023_the-first-week-of-any-diet-is-the-most-misleading-one",
        "primary_keyword": "why do you lose so much weight the first week of a diet",
        "current_first": "The first week is where people decide whether the plan is working. That decision is almost always based on the wrong evidence.",
        "opener": "Why do you lose so much weight the first week of a diet? Most of it is water, glycogen, and a noisier scale — not fat.",
        "new_first": "Why do you lose so much weight the first week of a diet? Most of it is water, glycogen, and a noisier scale — not fat. The first week is where people decide whether the plan is working. That decision is almost always based on the wrong evidence.",
    },
    "difference-between-weight-loss-and-fat-loss": {
        "package_basename": "wave_catchup_024_losing-weight-is-not-the-same-as-getting-leaner",
        "primary_keyword": "what's the difference between weight loss and fat loss",
        "current_first": "At one point in the middle of my transformation, I weighed the same for eight weeks. My clothes stopped fitting anyway.",
        "opener": "What's the difference between weight loss and fat loss? One moves the scale; the other actually changes how you look.",
        "new_first": "What's the difference between weight loss and fat loss? One moves the scale; the other actually changes how you look. At one point in the middle of my transformation, I weighed the same for eight weeks. My clothes stopped fitting anyway.",
    },
    "how-to-eat-at-social-events-on-a-diet": {
        "package_basename": "wave_catchup_026_how-do-i-eat-normally-at-social-events",
        "primary_keyword": "how to eat at social events on a diet",
        "current_first": "Most people think a dinner out is where the diet breaks. Usually, the dinner is the smallest part of the problem. The damage happens before and after, not at it.",
        "opener": "Here's how to eat at social events on a diet without making the dinner the villain. The damage usually happens around the dinner.",
        "new_first": "Here's how to eat at social events on a diet without making the dinner the villain. The damage usually happens around the dinner. Most people think a dinner out is where the diet breaks. Usually, the dinner is the smallest part of the problem. The damage happens before and after, not at it.",
    },
    "how-to-stay-at-your-goal-weight-long-term": {
        "package_basename": "wave_catchup_027_the-kind-of-person-who-stays-at-their-goal-weight",
        "primary_keyword": "how to stay at your goal weight long term",
        "current_first": "I have met people who held their weight off for five, ten, fifteen years. They do not look like the motivational content suggests. They seem, most of the time, a little bored.",
        "opener": "Here's how to stay at your goal weight long term, in the unglamorous version: it looks more like routine than willpower.",
        "new_first": "Here's how to stay at your goal weight long term, in the unglamorous version: it looks more like routine than willpower. I have met people who held their weight off for five, ten, fifteen years. They do not look like the motivational content suggests. They seem, most of the time, a little bored.",
    },
    "why-did-i-stop-losing-weight-at-3-months": {
        "package_basename": "wave_catchup_028_why-you-stop-losing-weight-around-month-three",
        "primary_keyword": "why did I stop losing weight at 3 months",
        "current_first": "Most diets slow down around month three. Not because effort dropped. Not because the plan got worse. The body has simply become better at operating on less.",
        "opener": "Why did I stop losing weight at 3 months on a plan that worked in week one? Mostly because the body adapted to it.",
        "new_first": "Why did I stop losing weight at 3 months on a plan that worked in week one? Mostly because the body adapted to it. Most diets slow down around month three. Not because effort dropped. Not because the plan got worse. The body has simply become better at operating on less.",
    },
    "how-to-tell-if-youre-hungry-or-bored": {
        "package_basename": "wave_catchup_029_am-i-actually-hungry-or-am-i-bored",
        "primary_keyword": "how to tell if you're hungry or bored",
        "current_first": "If you have ever opened the fridge at 4 p.m., stared into it, and closed it without eating, you already know the question is real. Most of the time, it is not hunger. It is something else wearing hungers costume.",
        "opener": "Here's how to tell if you're hungry or bored standing at the open fridge. The cue is almost never in the stomach.",
        "new_first": "Here's how to tell if you're hungry or bored standing at the open fridge. The cue is almost never in the stomach. If you have ever opened the fridge at 4 p.m., stared into it, and closed it without eating, you already know the question is real. Most of the time, it is not hunger. It is something else wearing hungers costume.",
    },
    "how-much-protein-do-i-need-to-lose-fat": {
        "package_basename": "wave_catchup_030_how-much-protein-do-i-actually-need-to-lose-fat",
        "primary_keyword": "how much protein do I need to lose fat",
        "current_first": "Protein is the only macronutrient the internet agrees on. Unfortunately, the internet also cannot agree on how much of it you actually need. The truth is narrower than both.",
        "opener": "How much protein do I need to lose fat? Less than the influencer math sells, more than the food pyramid ever recommended.",
        "new_first": "How much protein do I need to lose fat? Less than the influencer math sells, more than the food pyramid ever recommended. Protein is the only macronutrient the internet agrees on. Unfortunately, the internet also cannot agree on how much of it you actually need. The truth is narrower than both.",
    },
    "why-are-my-workouts-harder-on-a-cut": {
        "package_basename": "wave_catchup_031_why-your-workouts-feel-harder-when-youre-dieting",
        "primary_keyword": "why are my workouts harder on a cut",
        "current_first": "People expect a training session to feel approximately the same from week to week. Once you are in a caloric deficit for more than a few weeks, that is not how it goes.",
        "opener": "Why are my workouts harder on a cut, even when the weights aren't heavier? Recovery changed, not the bar.",
        "new_first": "Why are my workouts harder on a cut, even when the weights aren't heavier? Recovery changed, not the bar. People expect a training session to feel approximately the same from week to week. Once you are in a caloric deficit for more than a few weeks, that is not how it goes.",
    },
    "why-does-strength-increase-before-muscle-size": {
        "package_basename": "wave_catchup_032_why-your-strength-increases-before-your-shape-changes",
        "primary_keyword": "why does strength increase before muscle size",
        "current_first": "I added 15 kg to my deadlift in my first six weeks of training. I did not look meaningfully different. If you were showing up in a mirror expecting week-by-week change, you would think the gym was broken.",
        "opener": "Why does strength increase before muscle size? The nervous system gets organized weeks before the body looks different.",
        "new_first": "Why does strength increase before muscle size? The nervous system gets organized weeks before the body looks different. I added 15 kg to my deadlift in my first six weeks of training. I did not look meaningfully different. If you were showing up in a mirror expecting week-by-week change, you would think the gym was broken.",
    },
}
